// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9a2yE-dOSkI0osfpivi_73R9g5rxh0g',
    appId: '1:881056806755:web:8d73443f57c76cd9b40556',
    messagingSenderId: '881056806755',
    projectId: 'exam-0425',
    authDomain: 'exam-0425.firebaseapp.com',
    storageBucket: 'exam-0425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPN-hhl0oM5ZT2ddDaW79kWS4gttuekCQ',
    appId: '1:881056806755:android:1aed5ad244063165b40556',
    messagingSenderId: '881056806755',
    projectId: 'exam-0425',
    storageBucket: 'exam-0425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrGosP8Pu-6k2iSpXtjxerpI9J4sR4Uik',
    appId: '1:881056806755:ios:d96e8a638a6531f0b40556',
    messagingSenderId: '881056806755',
    projectId: 'exam-0425',
    storageBucket: 'exam-0425.firebasestorage.app',
    iosBundleId: 'com.example.exam0425',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrGosP8Pu-6k2iSpXtjxerpI9J4sR4Uik',
    appId: '1:881056806755:ios:d96e8a638a6531f0b40556',
    messagingSenderId: '881056806755',
    projectId: 'exam-0425',
    storageBucket: 'exam-0425.firebasestorage.app',
    iosBundleId: 'com.example.exam0425',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB9a2yE-dOSkI0osfpivi_73R9g5rxh0g',
    appId: '1:881056806755:web:18a311afb4c98f9ab40556',
    messagingSenderId: '881056806755',
    projectId: 'exam-0425',
    authDomain: 'exam-0425.firebaseapp.com',
    storageBucket: 'exam-0425.firebasestorage.app',
  );
}
